version: '3'

services:
  ctf-gateway-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-8.10.0}
    expose:
      - "9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ${ELK_PASSWORD:-changeme}
      KIBANA_PASSWORD: ${ELK_PASSWORD:-changeme}
      discovery.type: single-node
      xpack.security.enabled: "false"
    networks:
      - elk
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    # # needs privileged, better use fix.sh
    # sysctls:
    #   - vm.max_map_count=262144
    restart: always
    healthcheck:
      start_period: 15s
      test: ["CMD", "curl", "-f", "-u", "elastic:${ELK_PASSWORD:-changeme}", "-k", "http://localhost:9200"]
      interval: 10s
      timeout: 2s
      retries: 5

  # ctf-gateway-logstash:
  #   image: docker.elastic.co/logstash/logstash:${ELK_VERSION:-8.10.0}
  #   depends_on:
  #     ctf-gateway-elasticsearch:
  #       condition: service_healthy
  #   volumes:
  #     # - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   expose: 
  #     - "5044"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #     ELASTIC_PASSWORD: ${ELK_PASSWORD:-changeme}
  #     HTTP_HOST: "0.0.0.0"
  #   networks:
  #     - elk

  ctf-gateway-kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION:-8.10.0}
    depends_on:
      ctf-gateway-elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: ctf-gateway-kibana
      SERVER_HOST: "0.0.0.0"
      MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: true
      ELASTICSEARCH_HOSTS: '["http://ctf-gateway-elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${ELK_PASSWORD:-changeme}
    networks:
      - elk
    # volumes:
    #   - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    restart: always

  # app:
  #   build : ./app
  #   volumes:
  #     - ./app/:/usr/src/app
  #     - /usr/src/app/node_modules/ # make node_module empty in container
  #   command: npm start
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - elk

  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - ./nginx/config:/etc/nginx/conf.d
  #     - ./nginx/log:/var/log/nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   links:
  #     - app:app
  #   depends_on: 
  #     - app
  #   networks:
  #     - elk

  # filebeat:
  #   build: ./filebeat
  #   entrypoint: "filebeat -e -strict.perms=false"
  #   volumes:
  #     - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - ./nginx/log:/var/log/nginx
  #   networks:
  #     - elk
  #   depends_on: 
  #     - app
  #     - nginx
  #     - logstash
  #     - elasticsearch
  #     - kibana
  #   links: 
  #     - logstash

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
