version: '3'

services:
  ctf-gateway-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION:-8.10.0}
    expose:
      - "9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ${ELK_PASSWORD:-changeme}
      KIBANA_PASSWORD: ${ELK_PASSWORD:-changeme}
      discovery.type: single-node
      xpack.security.enabled: "false"
    networks:
      - elk
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    # # needs privileged, better use fix.sh
    # sysctls:
    #   - vm.max_map_count=262144
    restart: always
    healthcheck:
      start_period: 15s
      test: ["CMD", "curl", "-f", "-u", "elastic:${ELK_PASSWORD:-changeme}", "-k", "http://localhost:9200"]
      interval: 10s
      timeout: 2s
      retries: 5

  ctf-gateway-logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION:-8.10.0}
    depends_on:
      ctf-gateway-elasticsearch:
        condition: service_healthy
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    expose: 
      - "5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ${ELK_PASSWORD:-changeme}
      HTTP_HOST: "0.0.0.0"
    networks:
      - elk
    links:
     - "ctf-gateway-elasticsearch:elasticsearch"
    restart: always

  ctf-gateway-kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION:-8.10.0}
    depends_on:
      ctf-gateway-elasticsearch:
        condition: service_healthy
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      SERVER_NAME: ctf-gateway-kibana
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${ELK_PASSWORD:-changeme}
    networks:
      - elk
    links:
     - "ctf-gateway-elasticsearch:elasticsearch"
    restart: always

  ctf-gateway-nginx:
    image: owasp/modsecurity-crs:nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      # disable numerical host blocks
      - /dev/null:/etc/modsecurity.d/owasp-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
    environment:
      ERRORLOG: /var/log/nginx/error.log
      PORT: 65432
      BACKEND: http://localhost:8000
      PROXY_PRESERVE_HOST: off
    network_mode: host
    restart: always

  ctf-gateway-filebeat:
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION:-8.10.0}
    entrypoint: "filebeat -e -strict.perms=false"
    depends_on:
      ctf-gateway-elasticsearch:
        condition: service_healthy
      ctf-gateway-logstash:
        condition: service_started
      ctf-gateway-nginx:
        condition: service_started
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/log:/var/log/nginx
    networks:
      - elk
    links: 
      - "ctf-gateway-logstash:logstash"
      - "ctf-gateway-kibana:kibana"
    restart: always

  ctf-gateway-portainer:
    image: portainer/portainer-ce
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  portainer_data:
