filebeat.inputs:
- type: log
  paths:
    - /var/log/nginx/*.json
  tags: ["nginx", "json"]
  json:
    keys_under_root: true
    add_error_key: true

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

setup:
  kibana:
    host: "http://kibana:5601"
    username: "elastic"
    password: "CTF_34765938475_Password"
  dashboards:
    enabled: true